# Change these first
owner: mrvinceo # Your GitHub organization or username, where this repository lives
repo: ocaUptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: OCA Learn (VLE)
    url: https://learn.oca.ac.uk
  - name: OCA Spaces (Blogs)
    url: https://spaces.oca.ac.uk
  - name: OCA Main Site
    url: https://www.oca.ac.uk
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Panopto Media Service
    url: https://oca.cloud.panopto.eu
  - name: Gmail
    url: https://mail.google.com
  - name: Google Drive
    url: https://drive.google.com
  - name: Google Calendar
    url: https://calendar.google.com
  - name: OCA Padlet
    url: https://oca.padlet.org
  - name: OCA Zoom
    url: https://oca.zoom.us
  - name: Student Information System
    check: "tcp-ping"
    url: https://filemaker.oca.ac.uk
    port: 443
  - name: Showcase Gallery
    url: https://showcase.oca.ac.uk
  - name: OCA Projects
    url: https://projects.oca.ac.uk
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: services.oca.ac.uk
  # baseUrl: /your-repo-name
  logoUrl: https://www.oca.ac.uk/wp-content/themes/oca/images/oca-logo.png
  name: OCA Services Uptime
  introTitle: "This is the OCA Services uptime and status page. Please check here to see the status of any college services if you're encountering disruption."
  introMessage: "This status page uses the Open Source [upptime.js.org application](https://upptime.js.org)."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
